name: Deploy to dev
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and deploy to dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"

      - name: Build Go application
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server .

      - name: Build and push
        uses: nais/docker-build-push@423a915c9b72edf2ba848b88171ccb0489e2a40a # v0
        id: docker-build-push
        with:
          team: klage

      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@9850be311389ca754d9a9f2280615419d738c891 # v3
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VAR: image=${{ steps.docker-build-push.outputs.image }},version=${{ github.sha }}
